import type {
  AuditEvent,
  HandoverDocument,
  MaintenanceTask,
  ProductVersion,
  Project,
  SpecificationUpload,
  ExtractedHandoverItem,
} from "./types";

export const projects: Project[] = [
  {
    id: "prj-bayview",
    name: "Bayview Road New Build",
    address: "18 Bayview Road, Tauranga",
    clientName: "Amelia and Noah Smith",
    clientEmail: "amelia.smith@example.co.nz",
    projectType: "New residential build",
    handoverDate: "2026-07-22",
    status: "in_review",
    documentCount: 18,
    productCount: 24,
    openTasks: 7,
    lastActivity: "2026-06-14T09:15:00+12:00",
  },
  {
    id: "prj-kowhai",
    name: "Kowhai Street Renovation",
    address: "42 Kowhai Street, Hamilton",
    clientName: "Grace Patel",
    clientEmail: "grace.patel@example.co.nz",
    projectType: "Full renovation",
    handoverDate: "2026-08-05",
    status: "draft",
    documentCount: 9,
    productCount: 11,
    openTasks: 4,
    lastActivity: "2026-06-12T15:40:00+12:00",
  },
  {
    id: "prj-ridge",
    name: "Ridge Lane Reclad",
    address: "7 Ridge Lane, Auckland",
    clientName: "Elliot Williams",
    clientEmail: "elliot.williams@example.co.nz",
    projectType: "Reclad project",
    handoverDate: "2026-06-28",
    status: "published",
    documentCount: 26,
    productCount: 19,
    openTasks: 3,
    lastActivity: "2026-06-15T08:20:00+12:00",
  },
];

export const documents: HandoverDocument[] = [
  {
    id: "doc-ccc",
    projectId: "prj-bayview",
    name: "Code Compliance Certificate.pdf",
    type: "consent",
    size: "1.4 MB",
    uploadedAt: "2026-06-10",
    visibleToClient: true,
  },
  {
    id: "doc-heatpump",
    projectId: "prj-bayview",
    name: "Heat pump owner manual.pdf",
    type: "manual",
    size: "3.1 MB",
    uploadedAt: "2026-06-11",
    visibleToClient: true,
  },
  {
    id: "doc-window",
    projectId: "prj-bayview",
    name: "Window warranty schedule.pdf",
    type: "warranty",
    size: "860 KB",
    uploadedAt: "2026-06-13",
    visibleToClient: false,
  },
];

export const productVersions: ProductVersion[] = [
  {
    id: "prod-linea-v1",
    productName: "Linea Weatherboard",
    brand: "James Hardie",
    category: "Cladding",
    location: "Exterior envelope",
    warrantyPeriod: "15 years subject to installation and maintenance conditions",
    maintenanceSummary: "Wash exterior surfaces annually, more often in coastal zones.",
    voidConditions:
      "Incorrect installation, missed coating requirements, or poor maintenance may affect warranty cover.",
    confidenceScore: 94,
    confidenceLabel: "high",
    status: "approved",
    checkedAt: "2026-06-15",
    sources: [
      {
        title: "James Hardie NZ Linea Weatherboard",
        url: "https://www.jameshardie.co.nz/",
        sourceType: "manufacturer_page",
        official: true,
        nzSpecific: true,
      },
      {
        title: "James Hardie product warranty",
        url: "https://www.jameshardie.co.nz/",
        sourceType: "warranty_pdf",
        official: true,
        nzSpecific: true,
      },
    ],
    missingFields: [],
    reviewReason: "Official NZ manufacturer source and warranty guidance found.",
  },
  {
    id: "prod-dishwasher-v1",
    productName: "Freestanding Dishwasher",
    brand: "Fisher & Paykel",
    category: "Appliance",
    location: "Kitchen",
    warrantyPeriod: "2 years, model confirmation needed",
    maintenanceSummary: "Clean filters regularly and follow model-specific care guide.",
    voidConditions: "Misuse, unauthorised repairs, and non-domestic use may affect cover.",
    confidenceScore: 68,
    confidenceLabel: "medium",
    status: "needs_review",
    checkedAt: "2026-06-15",
    sources: [
      {
        title: "Fisher & Paykel dishwasher support",
        url: "https://www.fisherpaykel.com/nz/",
        sourceType: "manufacturer_page",
        official: true,
        nzSpecific: true,
      },
    ],
    missingFields: ["Exact model number", "Model-specific maintenance PDF"],
    reviewReason: "Multiple similar models found; builder should confirm the model.",
  },
  {
    id: "prod-tapware-v1",
    productName: "Bathroom mixer tap",
    brand: "Unknown",
    category: "Plumbing fitting",
    location: "Main bathroom",
    warrantyPeriod: "Unknown",
    maintenanceSummary: "No reliable product-specific care source found.",
    voidConditions: "Unknown",
    confidenceScore: 22,
    confidenceLabel: "blocked",
    status: "blocked",
    checkedAt: "2026-06-15",
    sources: [],
    missingFields: ["Brand", "Model", "Official warranty source", "Care guide"],
    reviewReason: "Product is too vague for a source-backed warranty record.",
  },
];

export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: "mnt-cladding-wash",
    projectId: "prj-bayview",
    title: "Wash exterior cladding",
    cadence: "Every 12 months",
    dueDate: "2027-06-15",
    requiredForWarranty: true,
    relatedProduct: "Linea Weatherboard",
    status: "upcoming",
  },
  {
    id: "mnt-gutters",
    projectId: "prj-bayview",
    title: "Clean gutters and downpipes",
    cadence: "Every 6 months",
    dueDate: "2026-12-15",
    requiredForWarranty: false,
    relatedProduct: "Roofing and drainage",
    status: "upcoming",
  },
  {
    id: "mnt-heatpump",
    projectId: "prj-ridge",
    title: "Service heat pump",
    cadence: "Every 12 months",
    dueDate: "2026-06-01",
    requiredForWarranty: true,
    relatedProduct: "Heat pump",
    status: "overdue",
  },
];

export const specificationUploads: SpecificationUpload[] = [
  {
    id: "spec-bayview-1",
    projectId: "prj-bayview",
    fileName: "Bayview Road specification.pdf",
    uploadedAt: "2026-06-15",
    status: "needs_review",
    extractedCount: 18,
    newItemCount: 5,
    matchedItemCount: 13,
  },
  {
    id: "spec-ridge-1",
    projectId: "prj-ridge",
    fileName: "Ridge Lane finishes schedule.pdf",
    uploadedAt: "2026-06-12",
    status: "accepted",
    extractedCount: 11,
    newItemCount: 2,
    matchedItemCount: 9,
  },
];

export const extractedHandoverItems: ExtractedHandoverItem[] = [
  {
    id: "item-cladding",
    specificationId: "spec-bayview-1",
    itemType: "product",
    title: "Linea Weatherboard",
    category: "Cladding",
    location: "Exterior envelope",
    extractedText: "Exterior cladding specified as James Hardie Linea Weatherboard with paint finish.",
    reviewReason: "Matched existing source-backed cladding record with high confidence.",
    matchedExistingRecord: "Linea Weatherboard",
    confidenceScore: 92,
    status: "auto_approved",
  },
  {
    id: "item-heatpump",
    specificationId: "spec-bayview-1",
    itemType: "product",
    title: "Ducted heat pump system",
    category: "Heating/cooling",
    location: "Ceiling services",
    extractedText: "Mechanical schedule references ducted heat pump system; exact model to confirm.",
    reviewReason: "Model is not specific enough for global approval; builder or admin should confirm the unit.",
    matchedExistingRecord: null,
    confidenceScore: 61,
    status: "admin_review",
  },
  {
    id: "item-cladding-maintenance",
    specificationId: "spec-bayview-1",
    itemType: "maintenance",
    title: "Wash exterior cladding",
    category: "Maintenance",
    location: "Exterior envelope",
    extractedText: "Maintenance note requires regular washing of exterior cladding surfaces.",
    reviewReason: "Maintenance task matched an existing cladding care requirement.",
    matchedExistingRecord: "Wash exterior cladding",
    confidenceScore: 86,
    status: "auto_approved",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "aud-1",
    projectId: "prj-bayview",
    actor: "Mia - Builder Admin",
    action: "AI draft created",
    detail: "Drafted product record for Fisher & Paykel dishwasher.",
    createdAt: "2026-06-15T09:10:00+12:00",
  },
  {
    id: "aud-2",
    projectId: "prj-bayview",
    actor: "Mia - Builder Admin",
    action: "Document uploaded",
    detail: "Added Window warranty schedule.pdf to Bayview Road New Build.",
    createdAt: "2026-06-13T14:22:00+12:00",
  },
  {
    id: "aud-3",
    projectId: "prj-ridge",
    actor: "Client",
    action: "Handover viewed",
    detail: "Elliot Williams opened the published handover pack.",
    createdAt: "2026-06-15T08:20:00+12:00",
  },
  {
    id: "aud-4",
    actor: "System",
    action: "Reminder queued",
    detail: "Heat pump service reminder moved to overdue sequence.",
    createdAt: "2026-06-14T07:00:00+12:00",
  },
];
